services:
  swagger-ui:
    profiles:
      - explicit
    image: swaggerapi/swagger-ui:latest
    environment:
      VALIDATOR_URL: null
    ports:
      - "8081:8080"
    volumes:
      - type: bind
        source: $PWD/docker/swagger/swagger-initializer.js
        target: /usr/share/nginx/html/swagger-initializer.js
      - type: bind
        source: $PWD/docker/api/openapi.yaml
        target: /usr/share/nginx/html/openapi.yaml
    restart: on-failure
  rapidoc:
    profiles:
      - explicit
    image: mrin9/rapidoc:latest
    ports:
      - "8082:80"
    environment:
      SPEC_URL: openapi.yaml
      RAPIDOC_OPTIONS: "theme=dark render-style=view show-header=false show-info=false allow-server-selection=false allow-authentication=false"
    volumes:
      - type: bind
        source: $PWD/docker/api/openapi.yaml
        target: /usr/share/nginx/html/openapi.yaml
    restart: on-failure